=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/locale.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ............................................................... -->
<!-- Locale specification DTD ......................................... -->
<!-- ............................................................... -->

<!--

PURPOSE:
      Locale Defn

-->

<!-- ............................................................... -->
<!-- Entities for characters and symbols ........................... -->

<!ENTITY % UNOModule
        'unoid                     CDATA              #REQUIRED'>
<!ENTITY % MessageID
        'msgid                     CDATA              #REQUIRED'>
<!ENTITY % RefLocale
        'ref                     CDATA              #REQUIRED'>
<!-- The locale referred to for the sub categories -->

<!ELEMENT DefaultName  (#PCDATA)>

<!-- Locale is made of different sub categories -->
<!ELEMENT Locale (LC_INFO, LC_CTYPE, LC_FORMAT, LC_COLLATION, LC_SEARCH, LC_CALENDAR, LC_CURRENCY,  LC_TRANSLITERATION, LC_MISC, LC_NumberingLevel, LC_OutLineNumberingLevel)>
<!ATTLIST Locale  version CDATA #REQUIRED>
<!-- Valid number -->

<!ELEMENT LC_INFO (Language, Country, Platform?, Varient?)>

<!ELEMENT Language (LangID, DefaultName) >
<!ELEMENT LangID (#PCDATA) >
<!-- LangID must be valid two letter language identifier  defined by ISO-639 -->

<!ELEMENT Country (CountryID, DefaultName) >
<!ELEMENT CountryID (#PCDATA) >
<!-- CountryID must be valid two letter country identifier  defined by ISO-3166 -->

<!ELEMENT Platform (PlatformID) >
<!ELEMENT PlatformID (#PCDATA) >
<!-- can be generic|unix|win32|macos -->

<!ELEMENT Varient (#PCDATA) >

<!ELEMENT LC_FORMAT (FormatElement+) >
<!ATTLIST LC_FORMAT %RefLocale;>
<!ATTLIST LC_FORMAT ReplaceFrom CDATA #REQUIRED>
<!-- Define placeholder for currency code -->
<!ATTLIST LC_FORMAT ReplaceTo CDATA #REQUIRED>
<!-- Currency code to be used to replace the placeholder -->

<!ELEMENT FormatElement   ( FormatCode, DefaultName?)>
<!ATTLIST FormatElement    %MessageID;>
<!ATTLIST FormatElement    default CDATA #REQUIRED >
<!ATTLIST FormatElement    type    CDATA #REQUIRED >
<!--    short   medium  long
    There may be up to three groups (type="short", type="medium", type="long")
    for each usage category defined. Each group, if defined, needs excactly one
    default. The type roughly determines the display string length, for example
    short, medium, and long date formats.
-->
<!ATTLIST FormatElement    usage    CDATA #REQUIRED >
<!--
Can be 	FIXED_NUMBER ,FRACTION_NUMBER ,PERCENT_NUMBER  	SCIENTIFIC_NUMBER
	CURRENCY ,DATE ,TIME ,DATE_TIME
-->
<!ATTLIST FormatElement formatindex  CDATA #REQUIRED>
<!--
    The following FormatElements must follow specific rules:

    All:
        The format indices 1..49 are reserved and, for backwards compatibility,
        MUST be used as stated in
        offapi/com/sun/star/i18n/NumberFormatIndex.idl.
        Note that 48 and 49 are used internally and must not be used in locale
        data XML files. All other formats have to be present.

    Of usage="DATE":
        formatindex="21" is used to edit already existing date data. In order
        to always edit the full century the long year YYYY code must be used.
        Furthermore, the format has to be of an editable type, of course, which
        means parseable. Therefore it should only contain DD, MM, YYYY and date
        separators, and the YMD default order is determined from the order
        encountered in this format.
        TODO: Future versions should make use of an edit="true" attribute
        instead of relying on this special requirement.

    Of usage="DATE_TIME":
        formatindex="47" is used to edit already existing combined date/time
        data. The requirements are the same as for formatindex="21" above.

    Of usage="CURRENCY":
        formatindices 12, 13, 14, 15, 17 with [$xxx-yyy] notation must use the
        xxx currency symbol that has the attribute
        usedInCompatibleFormatCodes="true".  The hexadecimal yyy LCID must be
        properly set. It can be found in project util module tools file
        tools/inc/lang.hxx.  You may verify the proper use of the xxx currency
        symbol with the AWK script
        i18npool/source/localedata/data/currency-check.awk, it mustn't display
        any output. If it does, then there's something wrong.
-->
<!ELEMENT FormatCode      (#PCDATA)>

<!-- Depricated
<!ELEMENT DateFormats     (FormatElement+)>
<!ELEMENT TimeFormats     (FormatElement+)>
<!ELEMENT NumberFormats   (FormatElement+)>
<!ELEMENT CurrencyFormats (FormatElement+)>
<!ELEMENT PercentFormats (FormatElement+)>
-->

<!ELEMENT LC_CALENDAR (Calendar+ ) >
<!ATTLIST LC_CALENDAR %RefLocale;>
<!ELEMENT Calendar (DaysOfWeek, MonthsOfYear, Eras, StartDayOfWeek, MinimalDaysInFirstWeek) >
<!ATTLIST Calendar %UNOModule;>
<!-- the unoid of a gregorian calendar MUST be lower case "gregorian" -->
<!ATTLIST Calendar default CDATA #REQUIRED >
<!ELEMENT DaysOfWeek (Day+)>
<!-- Sequence of days is important, MUST start with Sunday -->
<!ELEMENT Day (DayID, DefaultAbbrvName, DefaultFullName)>
<!ELEMENT DayID (#PCDATA)>
<!-- preferably the lower case abbreviated English name like sun for Sunday -->
<!ELEMENT DefaultAbbrvName (#PCDATA)>
<!ELEMENT DefaultFullName (#PCDATA)>
<!ELEMENT MonthsOfYear (Month+)>
<!ELEMENT Month (MonthID, DefaultAbbrvName, DefaultFullName)>
<!ELEMENT MonthID (#PCDATA)>
<!-- preferably the lower case abbreviated English name like jan for January -->
<!ELEMENT Eras (Era+)>
<!ELEMENT Era (EraID, DefaultAbbrvName, DefaultFullName)>
<!ELEMENT EraID (#PCDATA)>
<!-- if a calendar has special eras (like zh_TW ROC or ja_JP Gengou calendar)
     and a date before those eras is undefined, a leading (first) dummy era
     with EraID="Dummy" has to be defined to enable the number formatter to
     fall back to a gregorian calendar for those date values if the XCalendar
     implementation returns an era value of 0.
-->
<!ELEMENT StartDayOfWeek (DayID)>
<!-- MUST exactly match (case significant!) one of the DayID of DaysOfWeek -->
<!ELEMENT MinimalDaysInFirstWeek (#PCDATA)>

<!ELEMENT LC_CURRENCY (Currency+ ) >
<!ATTLIST LC_CURRENCY %RefLocale;>
<!ELEMENT Currency (CurrencyID, CurrencySymbol, BankSymbol, CurrencyName, DecimalPlaces)>
<!ATTLIST Currency  default CDATA #REQUIRED >
<!ATTLIST Currency  usedInCompatibleFormatCodes CDATA #REQUIRED >
<!-- if this currency is the one used in compatible number format codes with
     <member>FormatElement::formatIndex</member> values in the range 12..17.
     Those format codes are used to generate some old style currency format
     codes for compatibility with StarOffice5 and StarOffice4.
     Every locale data file MUST contain exactly one currency having this set to "true",
     and that currency MUST be used in format codes 12..17.
     For European countries using the EURo it MUST be the old currency, for example, DM.
-->
<!ELEMENT CurrencyID (#PCDATA)>
<!ELEMENT CurrencySymbol (#PCDATA)>
<!ELEMENT BankSymbol (#PCDATA)>
<!ELEMENT CurrencyName (#PCDATA)>
<!ELEMENT DecimalPlaces (#PCDATA)>

<!ELEMENT LC_CTYPE (Separators, Markers, TimeAM, TimePM,  MeasurementSystem)>
<!ATTLIST LC_CTYPE  %RefLocale;>
<!ATTLIST LC_CTYPE  %UNOModule;>
<!ELEMENT Separators (DateSeparator, ThousandSeparator, DecimalSeparator, TimeSeparator, Time100SecSeparator, ListSeparator, LongDateDayOfWeekSeparator, LongDateDaySeparator, LongDateMonthSeparator, LongDateYearSeparator)>
<!ELEMENT Markers (QuotationStart, QuotationEnd, DoubleQuotationStart, DoubleQuotationEnd)>
<!ELEMENT DateSeparator (#PCDATA)>
<!ELEMENT ThousandSeparator (#PCDATA)>
<!ELEMENT DecimalSeparator (#PCDATA)>
<!ELEMENT TimeSeparator (#PCDATA)>
<!ELEMENT Time100SecSeparator (#PCDATA)>
<!ELEMENT TimeAM (#PCDATA)>
<!ELEMENT TimePM (#PCDATA)>
<!ELEMENT ListSeparator (#PCDATA)>
<!ELEMENT QuotationStart (#PCDATA)>
<!ELEMENT QuotationEnd  (#PCDATA)>
<!ELEMENT DoubleQuotationStart (#PCDATA)>
<!ELEMENT DoubleQuotationEnd (#PCDATA)>
<!ELEMENT MeasurementSystem  (#PCDATA)>
<!ELEMENT LongDateDayOfWeekSeparator (#PCDATA)>
<!ELEMENT LongDateDaySeparator (#PCDATA)>
<!ELEMENT LongDateMonthSeparator (#PCDATA)>
<!ELEMENT LongDateYearSeparator (#PCDATA)>

<!ELEMENT LC_COLLATION (Collator*, CollationOptions?)>
<!ATTLIST LC_COLLATION %RefLocale;>
<!ELEMENT Collator EMPTY>
<!ATTLIST Collator  %UNOModule;>
<!ATTLIST Collator  default CDATA #REQUIRED >
<!ELEMENT CollationOptions (TransliterationModules+)>
<!ELEMENT TransliterationModules (#PCDATA)>

<!ELEMENT LC_SEARCH (SearchOptions?)>
<!ATTLIST LC_SEARCH %RefLocale;>
<!ELEMENT SearchOptions (TransliterationModules+)>

<!ELEMENT LC_TRANSLITERATION (Transliteration+)>
<!ATTLIST LC_TRANSLITERATION %RefLocale;>
<!ELEMENT Transliteration EMPTY>
<!ATTLIST Transliteration  %UNOModule;>

<!ELEMENT LC_MISC (ForbiddenCharacters?, ReservedWords)>
<!ATTLIST LC_MISC %RefLocale;>
<!ELEMENT ForbiddenCharacters (ForbiddenLineBeginCharacters, ForbiddenLineEndCharacters)>
<!ELEMENT ForbiddenLineBeginCharacters (#PCDATA)>
<!ELEMENT ForbiddenLineEndCharacters (#PCDATA)>

<!ELEMENT ReservedWords  (trueWord, falseWord, quarter1Word, quarter2Word, quarter3Word, quarter4Word, aboveWord, belowWord, quarter1Abbreviatio, quarter2Abbreviatio, quarter3Abbreviationnn, quarter4Abbreviation)>
<!-- order is significant! -->
<!ELEMENT trueWord (#PCDATA)>
<!ELEMENT falseWord (#PCDATA)>
<!ELEMENT quarter1Word (#PCDATA)>
<!ELEMENT quarter2Word (#PCDATA)>
<!ELEMENT quarter3Word (#PCDATA)>
<!ELEMENT quarter4Word (#PCDATA)>
<!ELEMENT aboveWord (#PCDATA)>
<!ELEMENT belowWord (#PCDATA)>
<!ELEMENT quarter1Abbreviation (#PCDATA)>    <!-- "Q1" (quarter), "T1" (trimestre), ... -->
<!ELEMENT quarter2Abbreviation (#PCDATA)>
<!ELEMENT quarter3Abbreviation (#PCDATA)>
<!ELEMENT quarter4Abbreviation (#PCDATA)>


<!--
the parameter NumType can have one of the following values:
0 = CHARS_UPPER_LETTER   EX: A, B, C, ....
1 = CHARS_LOWER_LETTER   EX: a, b, c, ....
2 = ROMAN_UPPER          EX: I, II, III, ....
3 = ROMAN_LOWER          EX: i, ii, iii, ....
4 = ARABIC               EX: 1, 2, 3, 4, .....
5 = NUMBER_ONE     numbering is invisible
6 = CHAR_SPECIAL   use a character from specified font
7 = PAGE_DESCRIPTOR  numbering is specified in page style
8 = BITMAP                numbering is displayed in bitmap graphic
9 = CHARS_UPPER_LETTER_N  EX: A, B, ...., AA, BB
10 = CHARS_LOWER_LETTER_N EX: a, b, ..., aa, bb, cc
11 = Transliteration, numbering is generated by transliteration service
12 = NatNum, numbering is generated by nativenumbersupplier service
13 = Numbering for fullwidth Arabic number
14 = Bullet for Circle Number
15 = Numbering for Chinese lower case number
16 = Numbering for Chinese upper case number
17 = Numbering for Traditional Chinese upper case number
18 = Bullet for Chinese Tian Gan
19 = Bullet for Chinese Di Zi
20 = Numbering for Japanese traditional number
21 = Bullet for Japanese AIU fullwidth
22 = Bullet for Japanese AIU halfwidth
23 = Bullet for Japanese IROHA fullwidth
24 = Bullet for Japanese IROHA halfwidth
25 = Numbering for Korean upper case number
26 = Numbering for Korean hangul number
27 = Bullet for Korean Hangul Jamo
28 = Bullet for Korean Hangul Syllable
29 = Bullet for Korean Hangul Circled Jamo
30 = Bullet for Korean Hangul Circled Syllable
-->

<!ELEMENT LC_NumberingLevel (NumberingLevel+ )>
<!ATTLIST LC_NumberingLevel %RefLocale;>
<!ELEMENT NumberingLevel EMPTY>
<!ATTLIST NumberingLevel Prefix CDATA #REQUIRED>
<!ATTLIST NumberingLevel NumType CDATA #REQUIRED>
<!ATTLIST NumberingLevel Suffix CDATA  #REQUIRED>
<!ATTLIST NumberingLevel Transliteration CDATA #REQUIRED>
<!ATTLIST NumberingLevel NatNum CDATA #REQUIRED>


<!ELEMENT LC_OutLineNumberingLevel (OutlineStyle+ )>
<!ATTLIST LC_OuterneNumberingLevel %RefLocale;>
<!ELEMENT OutlineStyle (OutLineNumberingLevel+)>
<!ELEMENT OutLineNumberingLevel EMPTY>
<!ATTLIST OutLineNumberingLevel Prefix CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel NumType CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel Suffix CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel BulletChar CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel BulletFontName CDATA   #REQUIRED>
<!ATTLIST OutLineNumberingLevel ParentNumbering CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel LeftMargin CDATA   #REQUIRED>
<!ATTLIST OutLineNumberingLevel SymbolTextDistance CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel FirstLineOffset CDATA  #REQUIRED >
<!ATTLIST OutLineNumberingLevel Transliteration CDATA #REQUIRED >
<!ATTLIST OutLineNumberingLevel NatNum CDATA #REQUIRED >

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/ar_LB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale versionDTD="2.0" allowUpdateFromCLDR="no" version="1.2">
<LC_INFO>
<Language>
<LangID>ar</LangID>
<DefaultName>Arabic</DefaultName>
</Language>
<Country>
<CountryID>LB</CountryID>
<DefaultName>Lebanon</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="ar_EG"/>
<LC_FORMAT ref="ar_EG" replaceTo="[$ل.ل.‏-3001]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_INDEX ref="ar_EG"/>
<LC_CALENDAR>
<Calendar unoid="gregorian" default="true">
<DaysOfWeek ref="ar_EG_gregorian"/>
<MonthsOfYear>
<Month>
<MonthID>jan</MonthID>
<DefaultAbbrvName>كانون الثاني</DefaultAbbrvName>
<DefaultFullName>كانون الثاني</DefaultFullName>
</Month>
<Month>
<MonthID>feb</MonthID>
<DefaultAbbrvName>شباط</DefaultAbbrvName>
<DefaultFullName>شباط</DefaultFullName>
</Month>
<Month>
<MonthID>mar</MonthID>
<DefaultAbbrvName>آذار</DefaultAbbrvName>
<DefaultFullName>آذار</DefaultFullName>
</Month>
<Month>
<MonthID>apr</MonthID>
<DefaultAbbrvName>نيسان</DefaultAbbrvName>
<DefaultFullName>نيسان</DefaultFullName>
</Month>
<Month>
<MonthID>may</MonthID>
<DefaultAbbrvName>أيار</DefaultAbbrvName>
<DefaultFullName>أيار</DefaultFullName>
</Month>
<Month>
<MonthID>jun</MonthID>
<DefaultAbbrvName>حزيران</DefaultAbbrvName>
<DefaultFullName>حزيران</DefaultFullName>
</Month>
<Month>
<MonthID>jul</MonthID>
<DefaultAbbrvName>تموز</DefaultAbbrvName>
<DefaultFullName>تموز</DefaultFullName>
</Month>
<Month>
<MonthID>aug</MonthID>
<DefaultAbbrvName>آب</DefaultAbbrvName>
<DefaultFullName>آب</DefaultFullName>
</Month>
<Month>
<MonthID>sep</MonthID>
<DefaultAbbrvName>أيلول</DefaultAbbrvName>
<DefaultFullName>أيلول</DefaultFullName>
</Month>
<Month>
<MonthID>oct</MonthID>
<DefaultAbbrvName>تشرين الأول</DefaultAbbrvName>
<DefaultFullName>تشرين الأول</DefaultFullName>
</Month>
<Month>
<MonthID>nov</MonthID>
<DefaultAbbrvName>تشرين الثاني</DefaultAbbrvName>
<DefaultFullName>تشرين الثاني</DefaultFullName>
</Month>
<Month>
<MonthID>dec</MonthID>
<DefaultAbbrvName>كانون الأول</DefaultAbbrvName>
<DefaultFullName>كانون الأول</DefaultFullName>
</Month>
</MonthsOfYear>
<Eras>
<Era>
<EraID>bc</EraID>
<DefaultAbbrvName>ق.م</DefaultAbbrvName>
<DefaultFullName>ق.م</DefaultFullName>
</Era>
<Era>
<EraID>ad</EraID>
<DefaultAbbrvName>م</DefaultAbbrvName>
<DefaultFullName>م</DefaultFullName>
</Era>
</Eras>
<StartDayOfWeek><DayID>sat</DayID></StartDayOfWeek>
<MinimalDaysInFirstWeek>1</MinimalDaysInFirstWeek>
</Calendar>
<Calendar unoid="hijri" default="false">
<DaysOfWeek ref="ar_EG_gregorian"/>
<MonthsOfYear ref="ar_EG_hijri"/>
<Eras ref="ar_EG_hijri"/>
<StartDayOfWeek><DayID>sat</DayID></StartDayOfWeek>
<MinimalDaysInFirstWeek>1</MinimalDaysInFirstWeek>
</Calendar>
</LC_CALENDAR>
<LC_CURRENCY>
<Currency default="true" usedInCompatibleFormatCodes="true">
<CurrencyID>ل.ل.‏</CurrencyID>
<CurrencySymbol>ل.ل.‏</CurrencySymbol>
<BankSymbol>LBP</BankSymbol>
<CurrencyName>Pound</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="ar_EG"/>
<LC_NumberingLevel ref="ar_EG"/>
<LC_OutLineNumberingLevel ref="ar_EG"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/sv_FI.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>sv</LangID>
<DefaultName>Swedish</DefaultName>
</Language>
<Country>
<CountryID>FI</CountryID>
<DefaultName>Finland</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="sv_SE"/>
<LC_FORMAT ref="sv_SE" replaceTo="[$mk-81D]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_CALENDAR>
<Calendar unoid="gregorian" default="true">
<DaysOfWeek>
<Day>
<DayID>sun</DayID>
<DefaultAbbrvName>sö</DefaultAbbrvName>
<DefaultFullName>söndag</DefaultFullName>
</Day>
<Day>
<DayID>mon</DayID>
<DefaultAbbrvName>må</DefaultAbbrvName>
<DefaultFullName>måndag</DefaultFullName>
</Day>
<Day>
<DayID>tue</DayID>
<DefaultAbbrvName>ti</DefaultAbbrvName>
<DefaultFullName>tisdag</DefaultFullName>
</Day>
<Day>
<DayID>wed</DayID>
<DefaultAbbrvName>on</DefaultAbbrvName>
<DefaultFullName>onsdag</DefaultFullName>
</Day>
<Day>
<DayID>thu</DayID>
<DefaultAbbrvName>to</DefaultAbbrvName>
<DefaultFullName>torsdag</DefaultFullName>
</Day>
<Day>
<DayID>fri</DayID>
<DefaultAbbrvName>fr</DefaultAbbrvName>
<DefaultFullName>fredag</DefaultFullName>
</Day>
<Day>
<DayID>sat</DayID>
<DefaultAbbrvName>lö</DefaultAbbrvName>
<DefaultFullName>lördag</DefaultFullName>
</Day>
</DaysOfWeek>
<MonthsOfYear>
<Month>
<MonthID>jan</MonthID>
<DefaultAbbrvName>jan</DefaultAbbrvName>
<DefaultFullName>januari</DefaultFullName>
</Month>
<Month>
<MonthID>feb</MonthID>
<DefaultAbbrvName>feb</DefaultAbbrvName>
<DefaultFullName>februari</DefaultFullName>
</Month>
<Month>
<MonthID>mar</MonthID>
<DefaultAbbrvName>mar</DefaultAbbrvName>
<DefaultFullName>mars</DefaultFullName>
</Month>
<Month>
<MonthID>apr</MonthID>
<DefaultAbbrvName>apr</DefaultAbbrvName>
<DefaultFullName>april</DefaultFullName>
</Month>
<Month>
<MonthID>may</MonthID>
<DefaultAbbrvName>maj</DefaultAbbrvName>
<DefaultFullName>maj</DefaultFullName>
</Month>
<Month>
<MonthID>jun</MonthID>
<DefaultAbbrvName>jun</DefaultAbbrvName>
<DefaultFullName>juni</DefaultFullName>
</Month>
<Month>
<MonthID>jul</MonthID>
<DefaultAbbrvName>jul</DefaultAbbrvName>
<DefaultFullName>juli</DefaultFullName>
</Month>
<Month>
<MonthID>aug</MonthID>
<DefaultAbbrvName>aug</DefaultAbbrvName>
<DefaultFullName>augusti</DefaultFullName>
</Month>
<Month>
<MonthID>sep</MonthID>
<DefaultAbbrvName>sep</DefaultAbbrvName>
<DefaultFullName>september</DefaultFullName>
</Month>
<Month>
<MonthID>oct</MonthID>
<DefaultAbbrvName>okt</DefaultAbbrvName>
<DefaultFullName>oktober</DefaultFullName>
</Month>
<Month>
<MonthID>nov</MonthID>
<DefaultAbbrvName>nov</DefaultAbbrvName>
<DefaultFullName>november</DefaultFullName>
</Month>
<Month>
<MonthID>dec</MonthID>
<DefaultAbbrvName>dec</DefaultAbbrvName>
<DefaultFullName>december</DefaultFullName>
</Month>
</MonthsOfYear>
<Eras>
<Era>
<EraID>bc</EraID>
<DefaultAbbrvName>f.Kr.</DefaultAbbrvName>
<DefaultFullName>f.Kr.</DefaultFullName>
</Era>
<Era>
<EraID>ad</EraID>
<DefaultAbbrvName>e.Kr.</DefaultAbbrvName>
<DefaultFullName>e.Kr.</DefaultFullName>
</Era>
</Eras>
<StartDayOfWeek>
<DayID>mon</DayID>
</StartDayOfWeek>
<MinimalDaysInFirstWeek>4</MinimalDaysInFirstWeek>
</Calendar>
</LC_CALENDAR>
<LC_CURRENCY ref="fi_FI"/>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="sv_SE"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/es_MX.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>es</LangID>
<DefaultName>Spanish</DefaultName>
</Language>
<Country>
<CountryID>MX</CountryID>
<DefaultName>Mexico</DefaultName>
</Country>
<Platform>
<PlatformID>generic</PlatformID>
</Platform>
<Varient></Varient>
</LC_INFO>
<LC_CTYPE ref="es_DO"/>
<LC_FORMAT ref="es_DO" replaceTo="[$$-80A]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_CALENDAR ref="es_AR"/>
<LC_CURRENCY>
<Currency default="true" usedInCompatibleFormatCodes="true">
<CurrencyID>$</CurrencyID>
<CurrencySymbol>$</CurrencySymbol>
<BankSymbol>MXN</BankSymbol>
<CurrencyName>Peso</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="es_ES"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/en_ZA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>en</LangID>
<DefaultName>English</DefaultName>
</Language>
<Country>
<CountryID>ZA</CountryID>
<DefaultName>South Africa</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="en_GB"/>
<LC_FORMAT ref="en_US" replaceTo="[$R-1C09]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_CALENDAR ref="en_US"/>
<LC_CURRENCY>
<Currency default="true" usedInCompatibleFormatCodes="true">
<CurrencyID>R</CurrencyID>
<CurrencySymbol>R</CurrencySymbol>
<BankSymbol>ZAR</BankSymbol>
<CurrencyName>Rand</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="en_US"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/en_IE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>en</LangID>
<DefaultName>English</DefaultName>
</Language>
<Country>
<CountryID>IE</CountryID>
<DefaultName>Ireland</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="en_GB"/>
<LC_FORMAT ref="en_GB" replaceTo="[$IR£-1809]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_INDEX ref="en_US"/>
<LC_CALENDAR>
<Calendar unoid="gregorian" default="true">
<DaysOfWeek ref="en_US_gregorian"/>
<MonthsOfYear ref="en_US_gregorian"/>
<Eras ref="en_US_gregorian"/>
<StartDayOfWeek>
<DayID>mon</DayID>
</StartDayOfWeek>
<MinimalDaysInFirstWeek>1</MinimalDaysInFirstWeek>
</Calendar>
</LC_CALENDAR>
<LC_CURRENCY>
<Currency default="false" usedInCompatibleFormatCodes="true">
<CurrencyID>IR£</CurrencyID>
<CurrencySymbol>IR£</CurrencySymbol>
<BankSymbol>IEP</BankSymbol>
<CurrencyName>Punt</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
<Currency default="true" usedInCompatibleFormatCodes="false">
<CurrencyID>euro</CurrencyID>
<CurrencySymbol>€</CurrencySymbol>
<BankSymbol>EUR</BankSymbol>
<CurrencyName>Euro</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="en_US"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/en_TT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>en</LangID>
<DefaultName>English</DefaultName>
</Language>
<Country>
<CountryID>TT</CountryID>
<DefaultName>Trinidad and Tobago</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="en_AU"/>
<LC_FORMAT ref="en_US" replaceTo="[$TT$-2C09]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_INDEX ref="en_US"/>
<LC_CALENDAR ref="en_US"/>
<LC_CURRENCY>
<Currency default="true" usedInCompatibleFormatCodes="true">
<CurrencyID>TT$</CurrencyID>
<CurrencySymbol>TT$</CurrencySymbol>
<BankSymbol>TTD</BankSymbol>
<CurrencyName>Dollar</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="en_US"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/nb_NO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>nb</LangID>
<DefaultName>Norwegian Bokm√•l</DefaultName>
</Language>
<Country>
<CountryID>NO</CountryID>
<DefaultName>Norway</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="no_NO"/>
<LC_FORMAT ref="no_NO" replaceTo="[$kr-414]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_CALENDAR ref="no_NO"/>
<LC_CURRENCY ref="no_NO"/>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="no_NO"/>
<LC_NumberingLevel ref="en_US"/>
<LC_OutLineNumberingLevel ref="en_US"/>
</Locale>

=== cactus-bm/libreoffice-core/i18npool/source/localedata/data/ar_SA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Locale SYSTEM 'locale.dtd'>
<Locale version="1.2">
<LC_INFO>
<Language>
<LangID>ar</LangID>
<DefaultName>Arabic</DefaultName>
</Language>
<Country>
<CountryID>SA</CountryID>
<DefaultName>Saudi Arabia</DefaultName>
</Country>
</LC_INFO>
<LC_CTYPE ref="ar_EG"/>
<LC_FORMAT ref="ar_EG" replaceTo="[$ر.س.‏-401]"/>
<LC_COLLATION ref="en_US"/>
<LC_SEARCH ref="en_US"/>
<LC_INDEX ref="ar_EG"/>
<LC_CALENDAR>
<Calendar unoid="gregorian" default="true">
<DaysOfWeek ref="ar_EG_gregorian"/>
<MonthsOfYear ref="ar_EG_gregorian"/>
<Eras ref="ar_EG_gregorian"/>
<StartDayOfWeek><DayID>sat</DayID></StartDayOfWeek>
<MinimalDaysInFirstWeek>7</MinimalDaysInFirstWeek>
</Calendar>
<Calendar unoid="hijri" default="false">
<DaysOfWeek ref="ar_EG_gregorian"/>
<MonthsOfYear ref="ar_EG_hijri"/>
<Eras ref="ar_EG_hijri"/>
<StartDayOfWeek><DayID>sat</DayID></StartDayOfWeek>
<MinimalDaysInFirstWeek>1</MinimalDaysInFirstWeek>
</Calendar>
</LC_CALENDAR>
<LC_CURRENCY>
<Currency default="true" usedInCompatibleFormatCodes="true">
<CurrencyID>ر.س.‏</CurrencyID>
<CurrencySymbol>ر.س.‏</CurrencySymbol>
<BankSymbol>SAR</BankSymbol>
<CurrencyName>Riyal</CurrencyName>
<DecimalPlaces>2</DecimalPlaces>
</Currency>
</LC_CURRENCY>
<LC_TRANSLITERATION ref="en_US"/>
<LC_MISC ref="ar_EG"/>
<LC_NumberingLevel ref="ar_EG"/>
<LC_OutLineNumberingLevel ref="ar_EG"/>
</Locale>
